main/products/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired

class ProductForm(FlaskForm):
    product_name = StringField('Ady', validators=[DataRequired()])
    product_price = StringField('Bahasy', validators=[DataRequired()])
    product_key = StringField('Harydyň kody', validators=[DataRequired()])
    product_type = StringField('Harydyň görnüşi', validators=[DataRequired()])
    product_sale = StringField('Arzanladyş(%)', validators=[DataRequired()])
    product_description = TextAreaField('Tanyşdyryş', validators=[DataRequired()])
    submit = SubmitField('Harydy goş')


class ProductUpdateForm(FlaskForm):
    product_name = StringField('Ady', validators=[DataRequired()])
    product_price = StringField('Bahasy', validators=[DataRequired()])
    product_key = StringField('Harydyň kody', validators=[DataRequired()])
    product_type = StringField('Harydyň görnüşi', validators=[DataRequired()])
    product_sale = StringField('Arzanladyş(%)', validators=[DataRequired()])
    product_description = TextAreaField('Tanyşdyryş', validators=[DataRequired()])
    submit = SubmitField('Tazelemek')

main/products/routes.py
from turtle import pos
from flask import render_template, Blueprint, request, redirect, url_for
from .forms import ProductForm, ProductUpdateForm
from main.models import Products
from main import db

products = Blueprint('products', __name__)

@products.route('/all_products/')
def all_products():
    our_products = Products.query.all()
    return render_template("products.html", our_products=our_products)

@products.route('/yuwunmak_ucin/')
def yuwunmak_ucin():
    clear_products = Products.query.filter_by(product_type=2)
    return render_template("clear_pro.html", clear_products=clear_products)

@products.route('/electronics_tel/')
def electronics_tel():
    tel_products = Products.query.filter_by(product_type=3)
    return render_template("electronics.html", tel_products=tel_products)

@products.route('/azyk_haryt/')
def azyk_haryt():
    azyk_products = Products.query.filter_by(product_type=1)
    return render_template("azyk_haryt.html", azyk_products=azyk_products)

@products.route('/product/<int:id>/delete/', methods=['GET', 'POST'])
def delete_product(id):
    print(id)
    delete_product = Products.query.get_or_404(id)
    print(delete_product)
    db.session.delete(delete_product)
    db.session.commit()
    our_products = Products.query.all()
    return render_template("products.html", our_products=our_products)


@products.route('/product/<int:id>/update/', methods=['GET', 'POST'])
def update_product(id):
    products = Products.query.get_or_404(id)
    form = ProductUpdateForm()
    if form.validate_on_submit():
        products.product_name = form.product_name.data
        products.product_price = form.product_price.data
        products.product_key = form.product_key.data
        products.product_type = form.product_type.data
        products.product_sale = form.product_sale.data
        products.description = form.product_description.data
        db.session.commit()
        clear_products = Products.query.filter_by(product_type=2)
        return render_template("clear_pro.html", clear_products=clear_products)
    elif request.method == 'GET':
        form.product_name.data = products.product_name
        form.product_price.data = products.product_price
        form.product_key.data = products.product_key
        form.product_type.data = products.product_type
        form.product_sale.data = products.product_sale
        form.product_description.data = products.description
        return render_template("edit_product.html", form=form)

@products.route('/add_product/', methods=['GET', 'POST'])
def add_products():
    form = ProductForm()
    if form.validate_on_submit():
        new_product = Products.query.filter_by(product_key=form.product_key.data).first()
        if new_product is None:
            new_product = Products(product_name=form.product_name.data, product_price=form.product_price.data, product_key=form.product_key.data, product_type=form.product_type.data, product_sale=form.product_sale.data, description=form.product_description.data)
            db.session.add(new_product)
            db.session.commit()
        name = form.product_name.data
        form.product_name.data = ''
        form.product_price.data = ''
        form.product_key.data = ''
        form.product_type.data = ''
        form.product_sale.data = ''
        form.product_description.data = ''
    title = "hi"
    return render_template('add_product.html', form=form)

main/templates/add_product.html
{% extends "base.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <div class="form-group">
                {{ form.product_name.label(class="form-control-label") }}
                {{ form.product_name(class="form-control form-control-lg") }}
            </div>
            <div class="form-group">
                {{ form.product_price.label(class="form-control-label") }}
                {{ form.product_price(class="form-control form-control-lg") }}
            </div>
            <div class="form-group">
                {{ form.product_key.label(class="form-control-label") }}
                {{ form.product_key(class="form-control form-control-lg") }}
            </div>
            <div class="form-group">
                {{ form.product_type.label(class="form-control-label") }}
                {{ form.product_type(class="form-control form-control-lg") }}
            </div>
            <div class="form-group">
                {{ form.product_sale.label(class="form-control-label") }}
                {{ form.product_sale(class="form-control form-control-lg") }}
            </div>
            <div class="form-group">
                {{ form.product_description.label(class="form-control-label") }}
                {{ form.product_description(class="form-control form-control-lg") }}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-primary") }}
        </div>
    </form>
</div>
{% endblock %}

main/templates/azyk_haryt.html
{% extends 'base.html' %}
{% block content %}
<h1>Azyk harytlar</h1>
<br/>
{% for product in azyk_products %} 
    <div class="shadow p-3 mb-5 bg-body rounded">
        <a href="#">{{ product.product_name }}</a></br>
        {{ product.product_price }}</br>
        {{ product.description }}</br>
        {{ product.product_sale }}</br>
        {{ product.dateAdded }}</br>
    </div>
{% endfor %}
{% endblock %}

main/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="/static/admin/plugins/bootstrap/css/bootstrap.min.css">
		<link href="/static/admin/css/style.css" rel="stylesheet" />
		<link href="/static/admin/plugins/scroll-bar/jquery.mCustomScrollbar.css" rel="stylesheet" />
		<link href="/static/admin/plugins/horizontal-menu/dropdown-effects/fade-down.css" rel="stylesheet">
		<link href="/static/admin/plugins/horizontal-menu/horizontalmenu.css" rel="stylesheet">
		<link href="/static/admin/plugins/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet" />
		<link href="/static/admin/plugins/accordion1/css/easy-responsive-tabs.css" rel="stylesheet">
		<link href="/static/admin/plugins/sidebar/sidebar.css" rel="stylesheet">
		<link href="/static/admin/plugins/iconfonts/plugin.css" rel="stylesheet" />
		<link href="/static/admin/plugins/iconfonts/icons.css" rel="stylesheet" />
		<link  href="/static/admin/fonts/fonts/font-awesome.min.css" rel="stylesheet">
		{% block css %}{% endblock %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">

    <title>Dukanlar</title>
  </head>
  <body>
    {% include 'navigation.html' %}
    </br>
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>

    <a href="#top" id="back-to-top"><i class="fa fa-angle-up"></i></a>
		<script src="/static/admin/plugins/jquery-3.2.1.min.js"></script>
		<script src="/static/admin/plugins/bootstrap/popper.min.js"></script>
		<script src="/static/admin/plugins/bootstrap/js/bootstrap.min.js"></script>
		<script src="/static/admin/plugins/jquery.sparkline.min.js"></script>
		<script src="/static/admin/plugins/circle-progress.min.js"></script>
		<script src="/static/admin/plugins/moment/moment.min.js"></script>
		<script src="/static/admin/plugins/counters/jquery.missofis-countdown.js"></script>
		<script src="/static/admin/plugins/counters/counter.js"></script>
		<script src="/static/admin/plugins/bootstrap-daterangepicker/daterangepicker.js"></script>
		<script src="/static/admin/plugins/horizontal-menu/horizontalmenu.js"></script>
		<script src="/static/admin/plugins/accordion1/js/easyResponsiveTabs.js"></script>
		<script src="/static/admin/plugins/scroll-bar/jquery.mCustomScrollbar.concat.min.js"></script>
		<script src="/static/admin/plugins/sidebar/sidebar.js"></script>
		{% block js %}{% endblock %}
   
  </body>
</html>

main/templates/clear_pro.html
{% extends 'base.html' %}
{% block content %}
<h1>Arassacylyk Serishdeleri</h1>
<br/>
{% for product in clear_products %} 
    <div class="shadow p-3 mb-5 bg-body rounded">
        <a href="#"><h4>Ady: {{ product.product_name }}</a></br></h4>
        <h4>Bahasy: {{ product.product_price }}</br></h4>
        <h4>Tanyshdyrys: {{ product.description }}</br></h4>
        <h4>Arzanladysh: {{ product.product_sale }}</br></h4>
        <h4>Goyulan wagty: {{ product.dateAdded }}</br></h4>
        <a href="{{ url_for('products.update_product', id=product.id) }}">Tazelemek</a>
        <a href="{{ url_for('products.delete_product', id=product.id) }}">Ayyrmak</a>
    </div>
{% endfor %}
{% endblock %}

main/templates/edit_product.html
{% extends "base.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <div class="form-group">
                {{ form.product_name.label(class="form-control-label") }}
                {{ form.product_name(class="form-control form-control-lg") }}
            </div>
            <div class="form-group">
                {{ form.product_price.label(class="form-control-label") }}
                {{ form.product_price(class="form-control form-control-lg") }}
            </div>
            <div class="form-group">
                {{ form.product_key.label(class="form-control-label") }}
                {{ form.product_key(class="form-control form-control-lg") }}
            </div>
            <div class="form-group">
                {{ form.product_type.label(class="form-control-label") }}
                {{ form.product_type(class="form-control form-control-lg") }}
            </div>
            <div class="form-group">
                {{ form.product_sale.label(class="form-control-label") }}
                {{ form.product_sale(class="form-control form-control-lg") }}
            </div>
            <div class="form-group">
                {{ form.product_description.label(class="form-control-label") }}
                {{ form.product_description(class="form-control form-control-lg") }}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-primary") }}
        </div>
    </form>
</div>
{% endblock %}

main/templates/electronics.html
{% extends 'base.html' %}
{% block content %}
<h1>Telefonlar</h1>
<br/>
{% for product in tel_products %} 
    <div class="shadow p-3 mb-5 bg-body rounded">
        <a href="#">{{ product.product_name }}</a></br>
        {{ product.product_price }}</br>
        {{ product.description }}</br>
        {{ product.product_sale }}</br>
        {{ product.dateAdded }}</br>
    </div>
{% endfor %}
{% endblock %}

main/templates/index.html
{% extends 'base.html' %}
{% block content %}
    
    <h1>Hello world</h1>

    <h1>Menin layan donerim</h1>

   
{% endblock %}

main/templates/navigation.html
<nav class="navbar navbar-expand-lg" style="background-color: #20f019;">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{ url_for('products.all_products') }}">Dükanlar<br/>.com</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="nav nav-pills">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Azyk harytlary</a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{{ url_for('products.azyk_haryt') }}">Bakja önümleri</a>
              <a class="dropdown-item" href="{{ url_for('products.azyk_haryt') }}">Gury ir-imişler</a>
              <a class="dropdown-item" href="{{ url_for('products.azyk_haryt') }}">Et dünyäsi</a>
              <a class="dropdown-item" href="{{ url_for('products.azyk_haryt') }}">Yaglar, yumurtga</a>
              <a class="dropdown-item" href="{{ url_for('products.azyk_haryt') }}">Nahar goşundylary</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Arassaçylyk serişdeler</a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{{ url_for('products.yuwunmak_ucin') }}">Diş saglygy</a>
              <a class="dropdown-item" href="{{ url_for('products.yuwunmak_ucin') }}">Yuwunulýan serişdeler</a>
              <a class="dropdown-item" href="{{ url_for('products.yuwunmak_ucin') }}">Gap-gaç serişdeler</a>
              <a class="dropdown-item" href="{{ url_for('products.yuwunmak_ucin') }}">Yuwujy serişdeler</a>
              <a class="dropdown-item" href="{{ url_for('products.yuwunmak_ucin') }}">Hajathana serişdeler</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Hojalyk harytlary</a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="#">Diş saglygy</a>
              <a class="dropdown-item" href="#">Yuwunulýan serişdeler</a>
              <a class="dropdown-item" href="#">Gap-gaç serişdeler</a>
              <a class="dropdown-item" href="#">Yuwujy serişdeler</a>
              <a class="dropdown-item" href="#">Hajathana serişdeler</a>
            </div>
          </li>
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Bezeg harytlary</a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="#">Bakja önümleri</a>
              <a class="dropdown-item" href="#">Gury ir-imişler</a>
              <a class="dropdown-item" href="#">Et dünyäsi</a>
              <a class="dropdown-item" href="#">Yaglar, yumurtga</a>
              <a class="dropdown-item" href="#">Nahar goşundylary</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Eşikler</a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="#">Erkek eşikler</a>
              <a class="dropdown-item" href="#">Aýal eşikler</a>
              <a class="dropdown-item" href="#">Çaga eşikler</a>
              <a class="dropdown-item" href="#">Köwüşler</a>
              <a class="dropdown-item" href="#">Gyş eşikler</a>
            </div>
          </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Sowgatlyklar</a>
            </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('products.electronics_tel') }}">Elektronika</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Arassaçylyk serişdeler</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('products.add_products') }}">Haryt goshmak</a>
          </li>
        </ul>
        <form class="form-inline">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

main/templates/products.html
{% extends 'base.html' %}
{% block content %}
<h1>Azyk harytlar</h1>
<br/>
{% for product in our_products %} 
    <div class="shadow p-3 mb-5 bg-body rounded">
        <a href="#">{{ product.product_name }}</a></br>
        {{ product.product_price }}</br>
        {{ product.description }}</br>
        {{ product.product_sale }}</br>
        {{ product.dateAdded }}</br>
    </div>
{% endfor %}
{% endblock %}